### ISSUE TITLE
好像有个bug 

### ISSUE THREAD

**Issue by chenyeah** [cnwangjie/better-onetab#1]
设置点击图标 为储存当前窗口 会有关闭所有标签并关闭浏览器行为

**Comment by cnwangjie** [comment]
@chenyeah 现在只发现了会在当前页面仅为标签列表时会关闭所有页面，现在已经不会储存标签列表页，应该解决了这个问题。如果还存在任何问题请再提issue哦(づ￣3￣)づ╭❤～

**Comment by chenyeah** [comment]
好的
