### ISSUE TITLE
I lost my onetab lists three times even though I synced the last time. I lost hundreds of precious links

### ISSUE THREAD

**Issue by techtsin** [cnwangjie/better-onetab#100]
扩展版本 (extension version): 
浏览器版本 (browser version): 
操作系统 (operating system): 
问题描述 (problem description): 
 
实际行为 (actual behavior): 
 
期望行为 (expected behavior): 
 
重现步骤 (reproduce step):

**Comment by cnwangjie** [comment]
Hi, I'm sorry to hear that. The sync service is not very stable in the current version. And Better OneTab will add links to browser history when you store them in default. You could try to find them in your browser history. Hope this could help you.

**Comment by techtsin** [comment]
I really like your app and I  find it a better choice than the original one and I will definitely use it in the future if it will be stable again since for a long time I didn't have any problem. But the last two three days something happened with its stability.Regards, techtsin
    Στις Σάββατο, 26 Ιανουαρίου 2019, 4:59:46 μ.μ. EET, ο χρήστης Yunhao Zhang <notifications@github.com> έγραψε:  
 
 
Hi, I'm sorry to hear that. The sync service is not very stable in the current version. And Better OneTab will add links to browser history when you store them in default. You could try to find them in your browser history. Hope this could help you.

**Comment by NadineNB** [comment]
Just lost hundreds of links myself using the sync feature... Will come back to the app in the future.

**Comment by cnwangjie** [comment]
I released a new version try to fix it. Please refer: https://github.com/cnwangjie/better-onetab/issues/121#issuecomment-488599916
