### ISSUE TITLE
Duplicate lists.

### ISSUE THREAD

**Issue by jaccarmac** [cnwangjie/better-onetab#102]
扩展版本 (extension version): 1.3.12
浏览器版本 (browser version): Chrome dev 73.0.3679.0
操作系统 (operating system): Gentoo Linux 4.14.83
问题描述 (problem description): Lists occasionally get duplicated when opening the extension page.
 
实际行为 (actual behavior): Sometimes opening the extension page duplicates my tab lists. I've noticed it happens especially when I store one tab while there is already a list stored. Usually reloading the page fixes the issue, but if I drag the one tab into the list to combine the lists then reload, I get three lists.

1. The new, combined list.
2. A list of the one tab I stored.
3. The old list without that single tab.
 
期望行为 (expected behavior): Tab lists only get displayed once when pulled from storage.
 
重现步骤 (reproduce step): No need for sync. Not exactly sure how to reproduce reliably as it is intermittent. Create a list then open the extension until it duplicates. See that it turns back to one list after a reload.

**Comment by cnwangjie** [comment]
Hi. I cannot reproduce it currently. But I'll notice it in future. The new version (1.4.x) was published. Could you update your extension to the latest version and try again? Hope you can provide further information if it still exists. Thank you.

**Comment by jaccarmac** [comment]
Haven't been able to repro in the new version, will reopen if I encounter the bug.
