### ISSUE TITLE
Share all my data to boss.cnwangjie.com

### ISSUE THREAD

**Issue by devz3r0** [cnwangjie/better-onetab#103]
扩展版本 (extension version): 1.4.0 on firefox/addon/better-onetab/
浏览器版本 (browser version): all
操作系统 (operating system): all
问题描述 (problem description): Dialogbox appears who tells me, the new version of the addon wants
share all my data for boss.cnwangjie.com
 https://i.imgur.com/yt1qNVW.png
实际行为 (actual behavior): share all my data to unknown destination
 
期望行为 (expected behavior): no external access for my data
 
重现步骤 (reproduce step): update addon

**Comment by cnwangjie** [comment]
Hi, I think the content of the notification is "read all data on boss.cnwangjie.com" actually. It is the domain of Better OneTab Sync Service. It won't share your data instead read your data on boss.cnwangjie.com domain. This permission used to get token after you authorization.

You can learn more details about this permission with the following link:

https://developer.chrome.com/extensions/content_scripts

Besides, you can browse all permission that this extension needed in

https://github.com/cnwangjie/better-onetab/blob/master/src/manifest.json

Hope this could help you.
