### ISSUE TITLE
Drag and drop not working in 1.4.0

### ISSUE THREAD

**Issue by geoervin** [cnwangjie/better-onetab#106]
扩展版本 (extension version): 1.4.0
浏览器版本 (browser version): Chrome 72.0.3626.81 (beta) others also tested
操作系统 (operating system): Windows 10
问题描述 (problem description): Drag operation does not complete. Both between lists and reordering in a list shows the correct animation but snaps back to original state
 
实际行为 (actual behavior): Drag between lists does not move an item. Reordering via drag and drop does not change list state.
 
期望行为 (expected behavior): An item dragged to a new location would "stick"" where it is placed. A list that has no items after a drag/drop move would  be removed
 
重现步骤 (reproduce step):Open onetab lists. Click on left side of a list item where the 4 arrow  icon is present. Hold button and move item to another list or position that the interface allows. Release mouse button

**Comment by cnwangjie** [comment]
Hi, thank you very much for your reports. I've published a new version with the patch fixes this. The new version (1.4.x) has huge changes to the old version (1.3.x). It is welcome to report it if you find any problems.
