### ISSUE TITLE
Is synchronization encrypted client-side?

### ISSUE THREAD

**Issue by jimbo1qaz** [cnwangjie/better-onetab#107]
扩展版本 (extension version): 1.4.0

Is synchronization encrypted on the browser-side, using a token which cannot be accessed unless someone hacks my Github/Google account? I don't want you or hackers to be able to access my saved tab list.

**Comment by cnwangjie** [comment]
Yes, all communication between the client and the server is restricted to use https. This ensures that your data is encrypted during transmission.

**Comment by cnwangjie** [comment]
Data will only be encrypted at the time of transmission. The user did not provide any keys for decrypting obviously. It is useless to take a fixed secret key encryption. For content stored in the database, if anyone has access to the database he can know the contents. But that is not easy to happen. :)
