### ISSUE TITLE
Please explain how Sync Setting and Sync List work?

### ISSUE THREAD

**Issue by snakyjake1** [cnwangjie/better-onetab#11]
Please explain how Sync Setting and Sync List work in Better OneTab options?

Thank you.

**Comment by cnwangjie** [comment]
@snakyjake1 Hi! It uses chrome provided sync service. 

This is the chrome api doc: https://developer.chrome.com/extensions/storage

This is the code about how better onetab use it: https://github.com/cnwangjie/better-onetab/blob/master/src/common/storage.js#L6-L29

Hope this can help you.
