### ISSUE TITLE
better-onetab all tabs disappeared

### ISSUE THREAD

**Issue by elegansCten** [cnwangjie/better-onetab#115]
Hi,
I have Better-onetab on Firefox 66ß / mac mojave, and I see that all tabs stored disappeared, I want to restore but I dont know where is the directory they are stocked.

**Comment by cnwangjie** [comment]
Hi, sorry for late reply. The browser storage file is not stored in plain text. If your storage still exists you could enter the following code in the console to display them.

```js
chrome.storage.local.get(null, console.log)
// or
await browser.storage.local.get() // only could be used in Firefox
```

Better OneTab will add links to browser history when you store them in default. You could try to find them in your browser history. Hope this could help you.

Besides, it is kind if you are willing to provide detail information about how your tabs are disappeared. Such as what you did before tabs are disappeared or they are disappeared directly after you open the browser without any operation. It could help me checks the reason and avoids it in the future.

Thank you.

**Comment by VicerExciser** [comment]
April 1st and this is still an issue for me. Has happened twice now in the past week. Unsure of what actions may have incurred this behavior but there is a possibility that the browser was closed (Firefox -> Quit Firefox) before the Better OneTab interface was closed. Also on a Mac (High Sierra running Firefox Quantum 66.0.2).

**Comment by cnwangjie** [comment]
I released a new version try to fix it. Please refer: https://github.com/cnwangjie/better-onetab/issues/121#issuecomment-488599916
