### ISSUE TITLE
Sync with (insert cloud service of choice)?

### ISSUE THREAD

**Issue by unabatedshagie** [cnwangjie/better-onetab#12]

**Comment by cnwangjie** [comment]
@unabatedshagie It is a great idea. I am developing a sync server and trying to sync with google drive.

**Comment by aloasut** [comment]
google drive is 1st choice.

**Comment by cnwangjie** [comment]
It provides an unlimited list sync service from v1.3.0. And also provide a way to save current list to google drive. You can have a try, and create a new issue if any problems occurred.

And it is welcome to share your new ideas.
