### ISSUE TITLE
数据丢失bug

### ISSUE THREAD

**Issue by lolstudio** [cnwangjie/better-onetab#125]
扩展版本 (extension version): 1.4.3
浏览器版本 (browser version):  72.0.3626.96（正式版本） （64 位）
操作系统 (operating system): Mac 10.10.5
问题描述 (problem description): 标签数据错乱，明明存储了，但再打开时链接不见了
 
实际行为 (actual behavior): 数据丢失
 
期望行为 (expected behavior): 数据不丢失
 
重现步骤 (reproduce step):Better OneTab中已有3个标签页（每个标签页下有>1条的链接），将一个新链接加到一个新标签页，将这个链接移动到3个标签页中的一个时能正常显示，再关闭Better OneTab，再打开，
就没看到那个链接，这个问题很严重，让人担心数据丢失不敢用了
![wx20190225-153225](https://user-images.githubusercontent.com/11715848/53321167-985df600-3912-11e9-9ae3-fe725d801b49.png)

**Comment by jaychsu** [comment]
+1 数据同丢失，但我不确定我怎么丢的。。。

操作的步骤是：

- 整理了一下我的所有的 list (70+ 的 links，包含 import 新的和移动旧的)
- 打开 Chrome Canary (这步不确定有没有影响)

**Comment by cnwangjie** [comment]
感谢反馈，我一直没法复现这个问题，但是参考了一些文章并review了我的代码之后我发现了可能导致数据丢失的问题。我刚发布了一个新版本尝试修复这个问题，非常欢迎测试新版本是否仍然具有这个问题。为了避免同样的问题开太多issue请后续的讨论和反馈移至#121
谢谢
