### ISSUE TITLE
Don't show remove confirmation when restoring list

### ISSUE THREAD

**Issue by pedroms** [cnwangjie/better-onetab#133]
When clicking the “Restore all in new window” it's a bit annoying to always show the remove confirmation alert. Usually I want to keep the lists intact, so I tend to dismiss that alert.

Can we have an option so it doesn't attempt to remove the list when restoring?

**Comment by cnwangjie** [comment]
Hi, do you turn on the option named "Confirm to remove list"? If so, you will need to confirm when your operation will remove the list. Could you try to check it?

**Comment by pedroms** [comment]
Yes, that works correctly and I'm already using that option. But what I
meant was to have a way to:
- not show any remove confirmation alert
- and not remove the list automatically

Essentially, when I restore all tabs in a list I want to keep them there
and not be bothered by a confirmation alert every time I do it. Does this
clarify the issue?

**Comment by cnwangjie** [comment]
You can try to pin the list. The list won't be removed when restoring if it is pinned.

**Comment by pedroms** [comment]
@cnwangjie that works, thanks!
