### ISSUE TITLE
Search by title

### ISSUE THREAD

**Issue by devargs** [cnwangjie/better-onetab#146]
I want to be able to search by the titles of my lists so that I can easily find my links.

Ex. I have tab lists with the word *important* in the title. I want to be able to quickly find all my lists related to something *important*.

**Comment by cnwangjie** [comment]
Hi, it could search by the title of lists now. Lists and links include the keyword will be shown when you search it. The result is whether a list or a link is represented by an icon on the right. Hope it could help you.
