### ISSUE TITLE
识别不出左右侧标签页

### ISSUE THREAD

**Issue by sickle12138** [cnwangjie/better-onetab#156]
扩展版本 (extension version): 1.4.3
浏览器版本 (browser version): 73.0.3683.86（正式版本）
操作系统 (operating system): win10
问题描述 (problem description): 识别不出左右侧标签页
 
实际行为 (actual behavior): 右击储存-保存右侧标签页为0不可点击
 
期望行为 (expected behavior): 保存右侧打开的所有标签页
 
重现步骤 (reproduce step):右击储存-保存右侧标签页

**Comment by cnwangjie** [comment]
我这里没法复现，请更新到最新版本再试一下，如果问题仍然存在请reopen这个issue
