### ISSUE TITLE
Firefox 66.0.2 标签页全部丢失

### ISSUE THREAD

**Issue by newage11** [cnwangjie/better-onetab#158]
扩展版本 (extension version): 1.43
浏览器版本 (browser version): Firefox 66.0.2
操作系统 (operating system): WIN10
问题描述 (problem description): 标签页全部丢失
 
实际行为 (actual behavior): 
 
期望行为 (expected behavior): 请问这个扩展有没有自动备份的文件，保存的标签页再哪一个路径？
 
重现步骤 (reproduce step):

**Comment by cnwangjie** [comment]
参考 #121
