### ISSUE TITLE
夜间模式优化

### ISSUE THREAD

**Issue by niudiewei** [cnwangjie/better-onetab#161]
您好，使用了您开发的产品倍感欣喜。

能否在夜间模式上添加一个时间监听，比如当地时间在20:00-7:00之间自动的设置为夜间模式。

如有打扰，还请谅解。

**Comment by cnwangjie** [comment]
感谢建议。其实是否启用夜间模式最好还是根据周围的环境光来决定，而根据所处环境不同环境光和时间并没有什么关系。当环境光变暗时用户可以很简单的点击右上角的图标切换黑色背景，这相对来说更实用一点。所以应该不会加根据时间调整的功能了。谢谢
