### ISSUE TITLE
希望增加标签管理功能

### ISSUE THREAD

**Issue by JadeVane** [cnwangjie/better-onetab#168]
感谢开发插件，比onetab好用多了。不过，在使用过程中有一些小问题，希望开发者能增加功能。

- 目前添加标签只能在标签列表里面直接输入新标签，然后才会跳出`create 标签`功能，希望能有一个标签的统一管理选项。
- 希望添加`删除标签`的功能

**Comment by cnwangjie** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [asd](https://trello.com/c/Ns1EdmMh/3-asd)
