### ISSUE TITLE
点击无反应  保存当前窗口所有标签页

### ISSUE THREAD

**Issue by imgwho** [cnwangjie/better-onetab#169]
扩展版本 (extension version): 
Version: 1.4.4 (Already the latest version)

浏览器版本 (browser version): 
chrome
版本 74.0.3729.131（正式版本） （64 位）
操作系统 (operating system):  win10 1809
问题描述 (problem description): 
 
实际行为 (actual behavior): 
 
期望行为 (expected behavior): 
 
重现步骤 (reproduce step):

**Comment by cnwangjie** [comment]
请提供下详细信息好吗？

**Comment by imgwho** [comment]
> 请提供下详细信息好吗？

对不起   更新后点击图标无反应  卸载重装也不行

**Comment by cnwangjie** [comment]
是指将`图标被点击的行为`设置为`保存当前窗口的所有标签页`后点击没有反应吗？可以试一下从右键菜单是否可以吗？

**Comment by imgwho** [comment]
![12](https://user-images.githubusercontent.com/16558238/57176156-f7963480-6e86-11e9-93b8-5fd0d28c2155.gif)
老哥你看吧   右键菜单是可以的

**Comment by imgwho** [comment]
好像是更新后就不行了   右键图标是可以用的  这是我的版本
![image](https://user-images.githubusercontent.com/16558238/57176167-31673b00-6e87-11e9-89da-37e2b54867c1.png)
![image](https://user-images.githubusercontent.com/16558238/57176173-3cba6680-6e87-11e9-86f4-4263958ae886.png)
![image](https://user-images.githubusercontent.com/16558238/57176181-45ab3800-6e87-11e9-8ae6-8d6b8709a7ee.png)
![image](https://user-images.githubusercontent.com/16558238/57176190-59ef3500-6e87-11e9-9e41-55a6b5b8295b.png)
然后我同步的标签页也不见了 老大有空看看吧  非常感谢回复 😹

**Comment by cnwangjie** [comment]
感谢反馈，下个版本修了。

**Comment by cnwangjie** [comment]
> 然后我同步的标签页也不见了

同步的标签不见了是指所有储存的数据都不见吗？

**Comment by imgwho** [comment]
> > 然后我同步的标签页也不见了
> 
> 同步的标签不见了是指所有储存的数据都不见吗？

回来了回来了   应该是卸载重装插件后   没有瞬间同步过来  过一段时间 就同步下来了   感谢老大
![image](https://user-images.githubusercontent.com/16558238/57176272-a6874000-6e88-11e9-84d4-a6821a626928.png)

**Comment by cnwangjie** [comment]
重装好像是会删除用户数据的。但是同步失效就很严重了。。。如果有发生数据丢失或者同步服务失效的情况请在#121 下面反馈。谢谢

**Comment by ACBingo** [comment]
+1 我也遇到同样的问题。插件版本1.4.4
chrome 版本 74.0.3729.131（正式版本） （64 位）

mac 14.4

**Comment by cnwangjie** [comment]
已在v1.4.5中修复
