### ISSUE TITLE
Import "OneTab" from Json does not work is greyed-out

### ISSUE THREAD

**Issue by sfinley7** [cnwangjie/better-onetab#170]
扩展版本 (extension version): 
浏览器版本 (browser version): 
操作系统 (operating system): 
问题描述 (problem description): 
 
实际行为 (actual behavior): 
 
期望行为 (expected behavior): 
 
重现步骤 (reproduce step):

**Comment by sfinley7** [comment]
firefox 66.0.3

Also it will not import from plain txt file

**Comment by cnwangjie** [comment]
Did you enter the content in the text area? The import button would be disabled if text area is empty. Please try it again and reopen this issue if it still exists. Thank you.

**Comment by sfinley7** [comment]
Ok, Looks I got the hang of it. You need "Better" -Instructions. All is fine now and I like the way it lays out. I have to admit that I am very impressed and very satisfied. Thank you for creating this option and choice for saving our tabs.
