### ISSUE TITLE
Store All Tab in Current Window not working when click on BetterOneTab icon

### ISSUE THREAD

**Issue by nbiabani** [cnwangjie/better-onetab#175]
1.4.4 (extension version): 
Chrome 73.0.3683.103 (browser version): 
Windows 10 (operating system):

**Comment by ACBingo** [comment]
+1

**Comment by JonahRo179** [comment]
I am having the same issue

**Comment by cnwangjie** [comment]
Thank you for your reports. It is a known problem (were reported in Chinese), I'll fix it in next version.
(this issue will be kept open until next version release to avoid more duplicate issue

**Comment by cnwangjie** [comment]
fix in v1.4.5
