### ISSUE TITLE
可否加个勾选还原的功能

### ISSUE THREAD

**Issue by ACBingo** [cnwangjie/better-onetab#176]
![image](https://user-images.githubusercontent.com/8175422/57432020-35200680-7267-11e9-95e4-fde963048094.png)

如图。
同样，增加针对已勾选的批量操作，比如删除之类的

**Comment by cnwangjie** [comment]
感谢建议，之前有人提过，忘了做了，下个版本可能会加上。已经有一些可用的多选操作了，点全选右边的三个点可以展开列表

**Comment by cnwangjie** [comment]
已在v1.4.5加入
