### ISSUE TITLE
crash on strange keyboard shortcut

### ISSUE THREAD

**Issue by caughran** [cnwangjie/better-onetab#177]
Added a control+alt+shift+! shortcut for "enable the extension". Keyboard shortcut window froze, then crashed Opera. When I try to get rid of this unlikely shortcut, entering any box for a keyboard shortcut crashes again.

扩展版本 (extension version):
浏览器版本 (browser version):
操作系统 (operating system):
问题描述 (problem description):

实际行为 (actual behavior):

期望行为 (expected behavior):

重现步骤 (reproduce step):

**Comment by cnwangjie** [comment]
It seems a problem with Opera. It crashed when you set the shortcut. There is no relation with the extension.
