### ISSUE TITLE
今天才发现，4月28日之后的标签全没有

### ISSUE THREAD

**Issue by Pa55w0rd** [cnwangjie/better-onetab#183]
今天才发现，4月28日之后的标签全没有
火狐 chrome都没有，都是到4月28日

**Comment by Pa55w0rd** [comment]
我每天都保存一些页面，都没有了

**Comment by Pa55w0rd** [comment]
这些页面全丢了么？现在测试也是保存不上的

**Comment by cnwangjie** [comment]
感谢反馈。最近有很多关于数据修改无法应用的反馈。但是之前的数据丢失就很严重了。请提供一下浏览器版本和扩展版本。

另外，`4月28号之后的标签全部没有`是指：

1. 今天使用时所有数据全部丢失
2. 还是还保留了部分数据
3. 还是从4月28号开始就无法保存数据

另外默认会在保存时把标签添加到浏览器历史记录，可以尝试从浏览器历史记录里找回部分数据。

**Comment by Pa55w0rd** [comment]
@cnwangjie

**Comment by Pa55w0rd** [comment]
@cnwangjie

**Comment by itplanes** [comment]
chrome 最新稳定版+插件最新稳定版也不能保存列表。保存后列表不显示

**Comment by Pa55w0rd** [comment]
@itplanes 我现在chrome和firefox都存在这个问题

**Comment by Pa55w0rd** [comment]
@cnwangjie  经常清理浏览器缓存
现在插件还是不能用

**Comment by cnwangjie** [comment]
谢反馈，刚刚发布了一个版本可能修复了这个问题，如果问题仍然存在欢迎再次反馈。
Thank you for your report. I've published a new version. Please reference [https://github.com/cnwangjie/better-onetab/issues/121#issuecomment-519410965](https://github.com/cnwangjie/better-onetab/issues/121#issuecomment-519410965)

If your problem still exists or there is no relation to this problem, please submit a new issue or reopen this issue.
