### ISSUE TITLE
tabs lost ...

### ISSUE THREAD

**Issue by irungentootoo** [cnwangjie/better-onetab#184]
tabs lost
synchronization "does not work" - if you can add some kind of synchronization indicator, (1 out of 40 in process 20 is ready)
Restarting chrome and list of just closed tabs were in the list, and there is no list. 
A better OneTab 1.4.5 eookhngofldnbnidjlbkeecljkfpmfpg

**Comment by irungentootoo** [comment]
reached the limit, a new group is created, I update the page, there is no tab group,

**Comment by cnwangjie** [comment]
Thank you for your report. I've published a new version. Please reference https://github.com/cnwangjie/better-onetab/issues/121#issuecomment-519410965

If your problem still exists or there is no relation to this problem, please submit a new issue or reopen this issue.
