### ISSUE TITLE
建议增加支付宝或微信的捐助渠道

### ISSUE THREAD

**Issue by Peter-JXL** [cnwangjie/better-onetab#185]
相信有不少使用者是中国人，然而我没比特币...其他支付方式也没有
不知道怎么联系你，因此开了个issue

**Comment by cnwangjie** [comment]
感谢支持，并不期望能得到捐助，O(∩_∩)O谢谢

GitHub上有留邮箱和博客地址，博客里有telegram和wx号，都可以联系到我
