### ISSUE TITLE
Tabs all lost? (Better-onetab 1.4.5 with Firefox Quantum 67.0 (64-bit) and Windows 10)

### ISSUE THREAD

**Issue by prunepasty** [cnwangjie/better-onetab#189]
Is there a way to restore the lost tabs?

Where is Better Onetab data stored on a PC?

Can the tabs be recovered?

Thank you.

**Comment by cnwangjie** [comment]
Please refer: https://github.com/cnwangjie/better-onetab/issues/121#issuecomment-488606985
