### ISSUE TITLE
No longer available in Firefox Add-ons

### ISSUE THREAD

**Issue by IlyaOrson** [cnwangjie/better-onetab#194]
扩展版本 (extension version): not applicable
浏览器版本 (browser version): firefox 67.0
操作系统 (operating system): linux (kubuntu)
问题描述 (problem description): this extension does not appear in the Add-on catalog of firefox and [the link](https://addons.mozilla.org/en-US/firefox/addon/better-onetab/) to the firefox version in the README is broken

实际行为 (actual behavior): not available

期望行为 (expected behavior): available to install

重现步骤 (reproduce step): try to look for this extension in [firefox catalog](https://addons.mozilla.org/firefox/)

**Comment by rluiten** [comment]
It's a shame, it does appear to still be available for Chrome.

**Comment by nostink** [comment]
I am trying to find this out too.  I just installed on one computer and wanted to install on my other computers but can longer find it for Firefox

**Comment by rpnfan** [comment]
No information from the developer about this? It's really bad, when one settles on a tool which looks to be on the rise and then to have that removed from one day to the other. It seemed so far to be on a very good way to become what OneTab was and much more / better...

**Comment by NadineNB** [comment]
Any timeline on when the Firefox extension will be available again?
