### ISSUE TITLE
I store my tabs and they are not Really stored in the Better-One tab. Your program is really unstable. You are not a Better one Tab

### ISSUE THREAD

**Issue by harryjojo** [cnwangjie/better-onetab#196]
扩展版本 (extension version):
浏览器版本 (browser version):
操作系统 (operating system):
问题描述 (problem description):

实际行为 (actual behavior):

期望行为 (expected behavior):

重现步骤 (reproduce step):

**Comment by standuncan** [comment]
this has happened to me often. Does anyone know how to make Better One Tab store our saved tabs? I've lost a LOT of valuable searches this way. It makes "better" one tab almost useless if it doesn't save the tabs.

**Comment by Pictor13** [comment]
> I store my tabs and they are not Really stored in the Better-One tab. Your program is really unstable. You are not a Better one Tab
>
> 扩展版本 (extension version):
> 浏览器版本 (browser version):
> 操作系统 (operating system):
> 问题描述 (problem description):
> 
> 实际行为 (actual behavior):
> 
> 期望行为 (expected behavior):
> 
> 重现步骤 (reproduce step):

This is the most useless opened issue I ever read on Github.
You open an issue, without giving ANY information, writing a verbose title that is JUST COMPLAINING about a FREE software that a guy is putting PERSONAL TIME & PASSION on.

Who do you think you are to come here, assuming you are entitled to criticise and demand stuff?

Did you put the minimal effort to read the damn PINNED issues, where your EXACT problem has been already reported and is being discussed and is tried to be fixed?

Seriously man, close this issue; and try harder to **give** something if you want to **get** something.
