### ISSUE TITLE
I had stored a number of tabs in the Better One Tab and I now open it and they are gone....Whats is happening???? 

### ISSUE THREAD

**Issue by harryjojo** [cnwangjie/better-onetab#197]
扩展版本 (extension version):
浏览器版本 (browser version):
操作系统 (operating system):
问题描述 (problem description):

实际行为 (actual behavior):

期望行为 (expected behavior):

重现步骤 (reproduce step):

**Comment by Pictor13** [comment]
Man, did you subscribe to Github just to spam useless complaints on an Issue Tracking System for a product that **you get for free**? 
This is not a forum; write your complaint on your Facebook page, if you don't have anything useful to say.

And close this issue, please.

**Comment by Pictor13** [comment]
Same here:
https://github.com/cnwangjie/better-onetab/issues/196

You opend two **consequent** issues, about the **same** problem, without giving **any** help, and **just** demanding.
There's something wrong in how you are using the portal, don't you think?
