### ISSUE TITLE
今天突然保存不了了！！《qq浏览器10.4》

### ISSUE THREAD

**Issue by BigBlackHardThick** [cnwangjie/better-onetab#199]
qq浏览器10.4. 谷歌内核70.0.3538.25\IE11.175.18362.0 今天突然不能保存了。保存当时显示保存了，一刷新，列表全没了！！怎么办？是否要换老版本浏览器。（过去保存的还在）

**Comment by BigBlackHardThick** [comment]
我的谷歌浏览器，版本：75.0.3770.80可以使用。。。。

**Comment by cnwangjie** [comment]
感谢反馈，刚刚发布了一个版本可能修复了这个问题，如果问题仍然存在欢迎再次反馈。
