### ISSUE TITLE
Option to prevent ignore pinned tab

### ISSUE THREAD

**Issue by StephaneArguin** [cnwangjie/better-onetab#2]
Please add an option to prevent Better-Onetab to store pinned tabs.

**Comment by cnwangjie** [comment]
@StephaneArguin Thank you for your suggestion. This is really a necessary option. This option has been added in v1.0.4.

**Comment by IlyaOrson** [comment]
I just installed version 1.2.1 on Firefox and Windows 7 but I can't find this option. Where is it available?

PD. Nice add-on!
