### ISSUE TITLE
Tabs storage 

### ISSUE THREAD

**Issue by colibris79** [cnwangjie/better-onetab#20]
Hi,
I just installed your extension in my Linux computer ant it works great. I would like to know where is my tabs data stored in order to make a local backup of it. 
I would also suggest a warning message when you clic on "Delete" a group of tabs. In case you just clicked by mistake. 
Thanks!

**Comment by cnwangjie** [comment]
@colibris79 Hi, the data stored in the chrome provided storage currently. You can use `chrome.storage.local.get('lists', console.log)` to get them. But also you can use the `Export / Import` function, it will help you get the lists and transform it into JSON format.

**Comment by cnwangjie** [comment]
I don't like the alert personally, but I'd like to add an option to enable a warning message if it is helpful for someone.

**Comment by colibris79** [comment]
Hi @cnwangjie. Thanks for your answer. An option to enable or not would be even better. About the data storage are there any files I could copy from my "chrome-browser/Default" folder in order to make the backup? I was thinking about setting up a cron task to save these files automatically everyday without having to export them myself

**Comment by cnwangjie** [comment]
The chrome provided stroage is a built-in database instead of a normal text file in filesystem. Although there is an API allow access the file on filesystem but it is really unnecessary. The better onetab can help you sync the list data use cloud service.

**Comment by colibris79** [comment]
I see. That would be nice as well, more automatic even : ) 
How can I sync my tabs with a cloud service? I am seeing in the "Options" tab that I can enable "Sync settings" and "Sync lists". How does that work?
And besides "Sync lists" it says "quota exceeded". How is that?

**Comment by cnwangjie** [comment]
see #11 and #12 

The chrome provided sync have the size limit (8KB). If the used storage size is more than the limit will display "quota exceeded". But I am working for sync with self hosted server and google drive.

**Comment by colibris79** [comment]
Nice... How about using another cloud storing besides google drive? I say it for the people who live in China. Well, thanks a lot for your answers and this nice extension

**Comment by cnwangjie** [comment]
Added option "alert before remove list" in v1.3.2
