### ISSUE TITLE
搜索功能：点击搜索出来的链接导致better-onetab卡死，无法使用

### ISSUE THREAD

**Issue by tanshion** [cnwangjie/better-onetab#202]
扩展版本 (extension version):
Better-onetab
Version: 1.4.5 (Already the latest version)
浏览器版本 (browser version):
Google Chrome 已是最新版本
版本 75.0.3770.90（正式版本） （64 位）
操作系统 (operating system):
mac
问题描述 (problem description):

实际行为 (actual behavior):

期望行为 (expected behavior):

重现步骤 (reproduce step):

**Comment by cnwangjie** [comment]
感谢反馈，刚发了一个版本，其中修复了这个问题。
Hi, it was caused by a bug in the upstream module. I've published a new version with the solution to this problem. Thank you for reporting.
