### ISSUE TITLE
Clicking the extension should send all tabs to extension, and open the extension

### ISSUE THREAD

**Issue by SimonGhoul** [cnwangjie/better-onetab#205]
Saves a few clicks. Click extension to send all, right click for more options and to open extension

There are also many issues with the wording. Why store selected tabs when you can't select tabs? Better to change it to "store this tab". Same with "store unselected tabs". Better to just "store other tabs"

I also like more the word "send" instead of store but store isn't bad

**Comment by mahoromax** [comment]
You can actually select multiple tabs
Press CTRL and click on multiple tabs, then rightclick symbol and you can store those selceted tabs

You can change the behaviour of the extension button in the settings. 
Setttings -> 'Behaviour when icon is clicked'

L2Read issue

**Comment by timtorChen** [comment]
Oh I do not know browser have such property , thanks @mahoromax 

What if show a popup when extension clicked, showing some options of saving tabs, such as 
"save this window "
"save selected tabs (with a small ❓ icon tells user select tab by pressing CTRL and click )"

Furthermore, adding some UI in popup adding/ overwrite tabs to specific list.

**Comment by SimonGhoul** [comment]
> You can actually select multiple tabs
> Press CTRL and click on multiple tabs, then rightclick symbol and you can store those selceted tabs
> 
> You can change the behaviour of the extension button in the settings.
> Setttings -> 'Behaviour when icon is clicked'
> 
> L2Read issue, can be closed

Oh that's cool!
