### ISSUE TITLE
FF Extension Removed?

### ISSUE THREAD

**Issue by LeeUnd** [cnwangjie/better-onetab#210]
I have reinstalled FF and copied over my backup but have lost all the tab lists. Any idea of how to get them back?

Also, why has the extension been removed from the FF store?

**Comment by cagefigter** [comment]
Yeah I was sad a while back when i couldnt find the FF extension.  not sure why it was pulled.

**Comment by Azarilh** [comment]
+
I wanna know why it's not available anymore for FF. At least it still works for me.

**Comment by maverick74** [comment]
Hi @cnwangjie 

Ise there any plans or ETA on fixing this?

At least let us know what happened to the addon? 
Has the firefox version been discontinued?
