### ISSUE TITLE
Ability to restore tabs in chrome incognito window

### ISSUE THREAD

**Issue by kaushr** [cnwangjie/better-onetab#211]

**Comment by kaushr** [comment]
Can you add an option to restore tabs in an incognito window when extension is allowed in incognito mode? my use case requires signing into same website with multiple accounts and this is only possible by using a separate window in incognito mode for each account.

**Comment by cnwangjie** [comment]
You can turn on the `enable in incognito mode` option in extension manage page.

The Better OneTab won't save the cookie of the site, so it cannot achieve it if you want to quickly change the account of the same site.
