### ISSUE TITLE
Storage unsuccessful and button not working 

### ISSUE THREAD

**Issue by mahoromax** [cnwangjie/better-onetab#213]
Not sure if it is a duplicate, but it results in tabs not being stored.

扩展版本 (extension version): 1.4.5
浏览器版本 (browser version): Version 75.0.3770.142  (64-Bit)
操作系统 (operating system): Win 10 Pro x64
问题描述 (problem description): 
实际行为 (actual behavior):
重现步骤 (reproduce step):
Upon click on the button ( is set to store all tabs of a window) only the "better one-tab" tab opens but tabs are still open and the list is not updated.
Closing the "better one-tab" tab closes the whole window (all tabs). But nothing gets listed.
 Rightclicking and choosing "store all tabs in current window"  has the same effect.

After this, while the "better one-tab" tab is still open,  going the rightclick method again, it will close the tabs apart from the addon one, and list them but with a wrong date.  After reloading the tablist the newly saved ones are gone. 

This doesnt happen all the time, sometimes a normal click on the button just closes all tabs and opens the addon tab, but nothing appears in the list.

The last saved tab list (that has stayed) is from the 5th of July for me.

The base functionality (saving tabs) is completely broken or me, so the addon is not usable atm :-/

**Comment by cnwangjie** [comment]
Thank you for your report. I've published a new version. Please reference [https://github.com/cnwangjie/better-onetab/issues/121#issuecomment-519410965](https://github.com/cnwangjie/better-onetab/issues/121#issuecomment-519410965)

If your problem still exists or there is no relation to this problem, please submit a new issue or reopen this issue.

**Comment by mahoromax** [comment]
Saving tabs does work again.

The non-uniform behaviour of the button, list updating, and tab closing still persists.
