### ISSUE TITLE
Storage issue

### ISSUE THREAD

**Issue by jadknight** [cnwangjie/better-onetab#215]
扩展版本 (extension version):
浏览器版本 (browser version):
操作系统 (operating system): Mac OS Mojave 10.14.6
问题描述 (problem description): First I tempted to sync my stored tab lists with my Github account then for optimization purpose (actually I used to do that very often with my 4 Gb of ram lol)  I closed the navigator to clean my laptop with "CleanMyMac" so I can continue my work smootly. I relaunched chrome I checked my list but I couldn't find my stored tab lists anymore, everything wiped :/... I can't even describe you the frustration (I have stored important links for work and research) more than 5h of managing tab lists and immigrating from the old Onetab, lost and evaporated... I think it's a big issue you should really see that! I liked the UX/UI with google material design, the dark mode... but unfortunately, with this bad experience, I go back to my old Onetab sorry guys!

实际行为 (actual behavior): Storage data wiped!

期望行为 (expected behavior): sync data with no loss!

重现步骤 (reproduce step):

**Comment by cnwangjie** [comment]
Thank you for your report. I've published a new version. Please reference [https://github.com/cnwangjie/better-onetab/issues/121#issuecomment-519410965](https://github.com/cnwangjie/better-onetab/issues/121#issuecomment-519410965)

If your problem still exists or there is no relation to this problem, please submit a new issue or reopen this issue.
