### ISSUE TITLE
无法保存或者更改标签页

### ISSUE THREAD

**Issue by YXH-YXH** [cnwangjie/better-onetab#217]
扩展版本 (extension version):1.4.5
浏览器版本 (browser version): 75.0.3770.100（正式版本） （64 位）
操作系统 (operating system): win10
问题描述 (problem description):
无法保存或者更改标签页
1.新添加进标签，一旦刷新消失
2.修改标签后，刷新复原
3.取消固定标签，刷新复原

实际行为 (actual behavior):
无法对应存在的标签页进行修改

不太清楚这是我的个例还是大家都有这种情况？

**Comment by cnwangjie** [comment]
已经有很多人反馈过这个问题，但是因为没法稳定复现不知道问题出在哪里。

**Comment by cnwangjie** [comment]
能否提供一下控制台中输入以下代码的输出？
```js
chrome.storage.local.get(null, a => console.log(JSON.stringify(a)))
```

**Comment by iir910** [comment]
能否提供旧版本下载？ 因为这问题是突然出现的。之后就一直都是如此。
不确定是扩展升级后，还是浏览器升级后导致的

**Comment by cnwangjie** [comment]
旧版可以在release页面下载

agunico <notifications@github.com> 于 2019年7月29日周一 20:52写道：

**Comment by cnwangjie** [comment]
@YXH-YXH @iir910 刚发了一个新版，可能解决了这个问题。如果问题仍然存在请再次反馈。

**Comment by iir910** [comment]
bug一切照旧，并没有改变

**Comment by cnwangjie** [comment]
@iir910 还是数据修改保存不上吗？之前是否使用过同步功能？之前的问题是在同步的时候有个锁没释放，导致数据修改无法应用。

**Comment by iir910** [comment]
@cnwangjie  我没找到稳定复现的方法。只能肯定：或早或晚。bug虽会迟到，但不会缺席。

**Comment by cnwangjie** [comment]
@iir910 确认使用的是1.4.6版本吗？之前的问题在于启动一段时间后会触发同步，进而导致锁未被释放。所以触发的时间不确定。现在同步过程仍然会加锁，所以在超时之前还是会出现数据未保存的情况。但是当超时之后依然会触发数据修改。不知道你的情况和以上描述是否相符？

**Comment by cnwangjie** [comment]
计划下个版本更换储存模型了，不再手动控制并发锁了。

**Comment by iir910** [comment]
@cnwangjie  的确是1.46版，因为我已经从chrome商店里重装扩展很多次了。肯定是最新版。

**Comment by cnwangjie** [comment]
@iir910 这可不歇了，我现在的是彻底没法复现了。上面说的符合你的情况吗？要不然加个vx或者tg详谈一哈

**Comment by cnwangjie** [comment]
@iir910 可方便试一下下面这个版本
https://drive.google.com/file/d/1QpKteAIZcCaFkIWLy3q1umJcW1YBp8R6/view?usp=sharing

**Comment by iir910** [comment]
@cnwangjie  发邮件给你了
