### ISSUE TITLE
Search from Better Onetab's Search Field not working ?

### ISSUE THREAD

**Issue by SgtRudolph** [cnwangjie/better-onetab#218]

**Comment by Pictor13** [comment]
I have the extension since a year or so.
Yet, the search was never implemented since then; I never had it working.

**Comment by SgtRudolph** [comment]
Its  a good extension !
I like it better than many of the others , don't give up !


Thanks,

WS

👍   😊

**Comment by cnwangjie** [comment]
Hi, it was caused by a bug in the upstream module. I've published a new version with the solutation of this problem. Thank you for reporting.
