### ISSUE TITLE
收取所有tab时如果检测当前标签是新标签页，希望不要添加到onetab的列表

### ISSUE THREAD

**Issue by lengthmin** [cnwangjie/better-onetab#22]
fork了之后也没怎么看懂，第一次接触，只好来提issue
***
## 需求：
一键收取所有tab时希望不要把新标签页也加进去，直接关掉就好了。  
## 场景：
刚打开浏览器，准备看自己上次存的标签页，点一下工具栏的onetab，以前储存的标签页倒是在，但是还多了一个固定好的新标签页。
![image](https://user-images.githubusercontent.com/13938334/44515761-f1e03080-a6f5-11e8-9999-ccee68826f29.png)

**Comment by cnwangjie** [comment]
感谢反馈，已计划增加黑名单功能

**Comment by cnwangjie** [comment]
BTW储存标签部分的代码在这里，欢迎PR一个存在localStorage的url exclusion feature :joy:

https://github.com/cnwangjie/better-onetab/blob/2bf409ebb5758cea09c11abd88da15ea5ca56d61/src/common/tabs.js#L62-L79

**Comment by lengthmin** [comment]
好哒~先学习一下chrome插件开发~

**Comment by lengthmin** [comment]
好哒
