### ISSUE TITLE
Behavior when "Restore List" is clicked

### ISSUE THREAD

**Issue by JS-Zheng** [cnwangjie/better-onetab#222]
The default behavior when the `Restore List` is clicked is to restore tabs and remove the list, but  it should provide a "keep the list options"  (just restore tabs without removing the list).

This is similar to the "Open" option of  "Behavior when item in a list is clicked", but for the `Restore List`.

**Comment by cnwangjie** [comment]
You can try to pin the list. If the list was pinned, the list won't be removed when click `restore list`.
