### ISSUE TITLE
better-onetab opens wrong tab when I click on them.

### ISSUE THREAD

**Issue by KsRyY** [cnwangjie/better-onetab#225]
扩展版本 (extension version): 1.4.6
浏览器版本 (browser version): 73.0.3683.86
操作系统 (operating system): deepin 15.11
问题描述 (problem description): As the title

实际行为 (actual behavior): When I click on the tabs inside the better-onetab list, it opens the link of next tab and the item of the link that actually needs to open disappeared.

我稍微翻译一下上面的东西(因为上面的英文描述可能不太清楚): 当我点击列表中的项目时, better-onetab打开的时列表中下一个项目的链接, 而本来应该打开的链接所属的项目消失了(我因此无法打开列表中的第一个项目)

期望行为 (expected behavior): Open the link that belongs to that item.

重现步骤 (reproduce step): Just install the extension, store some tabs, and the issue will be present.

**Comment by hieudang9** [comment]
that happened when I used 125% scale in Windows 10, so maybe it relevant to scale/zoom function.

**Comment by cnwangjie** [comment]
I cannot reproduce it in the Chrome 78. But it seems that many people encountered it. I'll review this problem.

**Comment by AprilViolet** [comment]
> I cannot reproduce it in the Chrome 78. But it seems that many people encountered it. I'll review this problem.

Yes, I also encountered this problem, the bookmarks opened again will be confused with the address of the label below, is to open the above label but the url address is the url of the label below.

[This is the gif I recorded, pay attention to the open label and the favorite label address.](https://s2.ax1x.com/2019/08/23/mBHprt.gif)

**Comment by KsRyY** [comment]
Yes. I also use Windows under 125% scale.

**Comment by cnwangjie** [comment]
@AprilViolet Thank you for your record. A new version with the patch has published.
