### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by zYeoman** [cnwangjie/better-onetab#227]
扩展版本 (extension version): 1.4.6
浏览器版本 (browser version): Chromium 74.0.3729.169
操作系统 (operating system): Windows 10
问题描述 (problem description): 
Uncaught TypeError: Assignment to constant variable.
    at exchanger.js:1
When import with onetab format.

重现步骤 (reproduce step): 
导入（兼容OneTab） `https://google.com/`

(问题在这 https://github.com/cnwangjie/better-onetab/blob/master/src/exchanger.js#L20-L22 把const改成var就好了）

**Comment by pchrzasz** [comment]
Same problem on my side -  all imports are not working.

**Comment by cnwangjie** [comment]
Hi, this is a known bug, caused by js-uglify. I'll publish a new version to fix it soon.

**Comment by cnwangjie** [comment]
A new version with the patch fixes this has published.

**Comment by cnwangjie** [comment]
> (问题在这 https://github.com/cnwangjie/better-onetab/blob/master/src/exchanger.js#L20-L22 把const改成var就好了）

@zYeoman 本身语法并没有任何问题，但是js-uglify在做压缩时错误地做了inline操作，导致构建后的代码报错。。。

**Comment by pchrzasz** [comment]
It is working now, thanks for fixing ;)
