### ISSUE TITLE
Too  Complicated and Lack of Shortcuts

### ISSUE THREAD

**Issue by wisliyao** [cnwangjie/better-onetab#229]
1. can't just click the button to use it (as OneTab)
2. No shortcuts

That's to say, I need at least click 3 step  to finally convert the tabs into a list.

**Comment by cnwangjie** [comment]
1. You can change the behavior of the icon was clicked in the options page.
2. You can set a keyboard shortcut in chrome / firefox extension management page.
3. You can just right click the icon or the page and click store selected tabs, it just requires you 2 click.

Hope this above could help you. Or if you have any other ideas you can share with us.
