### ISSUE TITLE
sync error

### ISSUE THREAD

**Issue by xiusin** [cnwangjie/better-onetab#244]
扩展版本 (extension version):  1.4.7 
浏览器版本 (browser version): EDGE DEV
操作系统 (operating system): Mac
问题描述 (problem description): Loss of data after synchronization

**Comment by djtlgucla** [comment]
same here

**Comment by PwrSrg** [comment]
Will **SYNC ever work**??  It has _never_ worked for me.
It just takes me to a dead site that times out.  https://boss.cnwangjie.com/login
