### ISSUE TITLE
开启同步的情况下，执行以下三个步骤导致保存的标签页丢失

### ISSUE THREAD

**Issue by kppomzh** [cnwangjie/better-onetab#249]
扩展版本 (extension version):1.4.7
浏览器版本 (browser version):Microsoft Edge with Chromium Beta
操作系统 (operating system):Windows10 1903

前提条件：开启Better Onetab 同步服务器

问题描述 (problem description):开启Better Onetab 同步服务器后，保存标签页并马上重启导致保存的标签页丢失。但不能确定是否一定和同步服务器有关。

实际行为 (actual behavior):
重启后打开浏览器，发现刚保存的全部标签页都丢失

期望行为 (expected behavior):
重启后仍然能恢复所有标签页

重现步骤 (reproduce step):
1.点击保存全部标签页
2.立刻关闭浏览器
3.在30秒内重启系统

**Comment by cnwangjie** [comment]
保存数据不是立即完成的。需要一些时间。可能在重现步骤的第二步「关闭浏览器」的时候数据仍没有保存完成。至少要等待标签页关闭。
