### ISSUE TITLE
Current sync rule description

### ISSUE THREAD

**Issue by cnwangjie** [cnwangjie/better-onetab#25]
### Current rule

 - Upload on local data modified
    - We hope the last upload time of the remote server is same as local
    - If not we will allow the user to select keep local data or remote data
 - Download every some time (current one minute)
    - We believe server data is we want and we will use remote data to replace local data directly
    - If there is a conflict we will not directly download remote data

### Disadvantage

 - Because the current data does not have storage granularity we need to transfer all the data every time

**Comment by aloasut** [comment]
双机冲突已经吃掉了我一部机的session了。。。请测试充分后才放出.

**Comment by cnwangjie** [comment]
@aloasut 抱歉测试确实还不够充分，个人维护不容易，还请麻烦帮忙测试。

新版本在登录时如果本地从未上传过但列表不为空，会先显示和远程的冲突，可以避免授权后直接覆盖本地。但是当前想实现一个完美的多终端同步还是比较困难。
