### ISSUE TITLE
Share as Web Page

### ISSUE THREAD

**Issue by Rekunan** [cnwangjie/better-onetab#255]
This extension is better compared to the Original Onetab, but there was one feature missing and that was the ability to share a list of tabs as a webpage. I was wondering if you could add that in.

**Comment by nicbentulan** [comment]
https://github.com/cnwangjie/better-onetab/issues/151

**Comment by Rekunan** [comment]
dang wtf this is over 2 years ago, must've been a GitHub noob back then

ty for reminding me of this lol
