### ISSUE TITLE
 Can the title be renamed，I really need it，3Q

### ISSUE THREAD

**Issue by justbeyourself** [cnwangjie/better-onetab#259]
Can the title be renamed，I really need it，3Q

**Comment by JaneSmith** [comment]
You can change the title of a tab list by expanding it and then clicking the "RETITLE LIST" button. Or did you mean something else?

**Comment by justbeyourself** [comment]
> You can change the title of a tab list by expanding it and then clicking the "RETITLE LIST" button. Or did you mean something else?

I mean，I want to rename the tab's title, not the tab list's title.
