### ISSUE TITLE
Tabs do not appear on the list

### ISSUE THREAD

**Issue by rayman89** [cnwangjie/better-onetab#27]
扩展版本 (extension version): 1.3.2
浏览器版本 (browser version): 62 release and 63 beta
操作系统 (operating system): windows 7 x64

When using any of the commands to send tabs to the one tab list they get closed but they do not appear on the list.

Also the addon button has no icon.

**Comment by cnwangjie** [comment]
I am very sorry, I did not notice some difference on firefox that caused better onetab not work. I have published a new version to make its basic function can work. But sync still cannot work on firefox. I will try to solve it.

**Comment by rayman89** [comment]
Thank you for the fix but now the send all tabs of this window and send tab from all windows is not working also the fixes are not working on firefox beta they only work on release.
