### ISSUE TITLE
Graphic bug

### ISSUE THREAD

**Issue by rayman89** [cnwangjie/better-onetab#29]
扩展版本 (extension version): 1.3.3
浏览器版本 (browser version): Firefox 62 & 63
操作系统 (operating system): Windows 7

When giving the tab set a name overlapping with the date occurs

![image](https://user-images.githubusercontent.com/5449042/45245963-5be70100-b2c4-11e8-9a30-a60e2cabd7ba.png)

**Comment by cnwangjie** [comment]
新版本进行了一些修改，但是分辨率太小样式上还是会有一些问题。
