### ISSUE TITLE
点击图标后，短时间没有响应，然后多点几次，最后出来多次标签

### ISSUE THREAD

**Issue by bigriverhorse** [cnwangjie/better-onetab#3]
![onetab2](https://user-images.githubusercontent.com/17559895/42416306-af349086-829d-11e8-8597-cd7dec5b55c2.png)

点击图标后，短时间没有响应，然后多点几次，最后出来多次标签

**Comment by bigriverhorse** [comment]
只是运行慢，大概10秒才出现，这10秒中可能点了好多下，所以出现了好多Tab页

**Comment by lolstudio** [comment]
点开logo到打开标签页速度好慢呀，建议提高标签页打开速度，感谢作者。

**Comment by cnwangjie** [comment]
@lolstudio 感谢反馈,我开发和使用过程中就出现过一些操作首次执行无效的现象,但是我也不清楚原因,现在一些操作通过在代码中进行两次调用来确保正常.

我会继续深入寻找原因,这个问题将作为一个long term performance issue

如果有任何明确的问题,欢迎新开issue提供完整复现流程
