### ISSUE TITLE
Handling multiple tab at once

### ISSUE THREAD

**Issue by rayman89** [cnwangjie/better-onetab#30]
Could you consider adding the functionality to select multiple tabs like with checkboxes using control+ click  and shift + click for quick selection to do stuff to them like deleting and re arranging?

Something like this

![image](https://user-images.githubusercontent.com/5449042/45246249-e11ee580-b2c5-11e8-90f4-0fce04c15bbf.png)

**Comment by Artistan** [comment]
I see similar actions a lot in my development! But with multiple actions.
I would suggest using a "With Selected" dropdown button with multiple actions like ...

- Open / Restore
- Open in New Window
- Create new list
- Copy Links
- Delete
- Move

I edited the html on the github dropdown to show an example of what I mean...

![image](https://user-images.githubusercontent.com/801349/46673750-19a13000-cba0-11e8-8027-62f6293d7395.png)

I usually see this action button at the bottom, under the checkboxes
