### ISSUE TITLE
把我的 TAB 全搞丢了，哎

### ISSUE THREAD

**Issue by thisiseast** [cnwangjie/better-onetab#32]
扩展版本 (extension version): 1.3.0
浏览器版本 (browser version): Version 68.0.3440.106 (Official Build) (64-bit)
操作系统 (operating system): MAC
问题描述 (problem description): 
一共开了两个 chrome 的窗口，其中一个窗口只有一个 tab，一个窗口开了几十个 tab。
点了 store all tabs in all windows，结果发现只有那一个 tab 被保存了下来，另一个窗口的几十个 tab 全没了。说真的有点蛋疼加生气

实际行为 (actual behavior): 
 
期望行为 (expected behavior): 
 
重现步骤 (reproduce step):

**Comment by thisiseast** [comment]
发现这个情况后我赶紧 command + shift + T 一直按才勉强恢复了二十个左右的 tab，其他的全没了。

有一个情况是，多数 tab 是我在安装这个插件之前打开的，有的已经打开好几个月了。

**Comment by cnwangjie** [comment]
十分抱歉QAQ，刚刚发了新版本修复了这个问题。
