### ISSUE TITLE
Popup simple list not working

### ISSUE THREAD

**Issue by rayman89** [cnwangjie/better-onetab#34]
扩展版本 (extension version): 1.3.4
浏览器版本 (browser version): 62 and 63
操作系统 (operating system): Win 7

If "popup simple list" is selected in options, when you press the addon button it just shows a white page like this

![image](https://user-images.githubusercontent.com/5449042/45265798-8b0d8780-b416-11e8-80a8-75190432c7d8.png)

**Comment by cnwangjie** [comment]
fixes

**Comment by rayman89** [comment]
I  noticed though that the popup is really small. 

![image](https://user-images.githubusercontent.com/5449042/45303710-0b49f080-b4dc-11e8-8e43-95d3d371b257.png)

Shouldn't that be bigger?

**Comment by cnwangjie** [comment]
It should display all lists actually. It is maybe a bug if its height is too low. :confused: 

And you can set it to restore on the new window.

**Comment by rayman89** [comment]
Yes the height is too low. Could you fix it please. Thank you.
