### ISSUE TITLE
buttons in sync page are not available

### ISSUE THREAD

**Issue by frossie74** [cnwangjie/better-onetab#35]
扩展版本 (extension version): 1.3.5
浏览器版本 (browser version): 69
操作系统 (operating system): windows 10
问题描述 (problem description): when i go to sync tab page, i click on github button, or google button "authorize" but nothing happen. 
 
实际行为 (actual behavior): nothing happen clicking on authorize button on sync page. Also with "save immediately"  nothing happen
 
期望行为 (expected behavior): 
 
重现步骤 (reproduce step):

**Comment by frossie74** [comment]
some versions ago it worked . No more with these new versions.

**Comment by cnwangjie** [comment]
Thank you for the report. Is any error displayed? Sometimes it will happen depending on the network. I am trying to avoid it.

**Comment by frossie74** [comment]
No errors displayed..i have the same errors on two pc on different networks. 
I think that this error comes from previous version. Any way to delete settings and data ? i tried to remove the extension with no success .

**Comment by cnwangjie** [comment]
ok, I realize it is possible to make this situation happen. It is mainly my mistake. I think it should not let the user handle it. I will try to avoid it in the new version. But if you can, try to run `chrome.storage.local.get(null, obj => chrome.storage.local.remove(Object.keys(obj)))` in the console. It maybe can solve this. But it will remove all data. If you have some stored tabs, you can export them first.

**Comment by frossie74** [comment]
mmmmm....i tried but nothing happen . maybe a syntax error ?

**Comment by cnwangjie** [comment]
I have the same situation here. I will try to fix it.

**Comment by cnwangjie** [comment]
Did you update the extension to the latest version? If so, it may be not the same problem as the before.

I know there still are some problems with this so I kept this issue open until now. And I am planning to rewrite the code about sync feature to decrease the problems.

**Comment by frossie74** [comment]
Yes i updated it but sync is not working anymore now and sync page is not available (white page).
Any way to work around the bug ? Or i have to wait the correction of the bug ? 
Thank you

**Comment by cnwangjie** [comment]
Sorry I can't reproduce the cases of neither the page of extension is white page white page or the popup oauth window is white. And I am not clear what is the reason of it and can't provide a solution. But it sometimes can't popup that the oauth page because it depends an API of chrome that probably has some compatibility problems. So I decided to try another way to process the authorization. 

It's pity that my first trial of the sync isn't good, but thanks for your trying it and reports. The new version will have better experience I think.

**Comment by Artistan** [comment]
just worked for me.
