### ISSUE TITLE
A new tab for the plugin page should be opened after the previously-opened page has already been used to access other sites.

### ISSUE THREAD

**Issue by thisiseast** [cnwangjie/better-onetab#37]
扩展版本 (extension version): 
浏览器版本 (browser version): 
操作系统 (operating system): 
问题描述 (problem description): 
 
实际行为 (actual behavior): 
 
期望行为 (expected behavior): 
 
重现步骤 (reproduce step):
A plugin page shows up after clicking the plugin icon, which is expected. However, clicking again the plugin icon would still switch to the tab previously opened for the plugin, even after I've opened other sites like google.com in the tab.

**Comment by cnwangjie** [comment]
Thanks for the report. It fixed in new version.
