### ISSUE TITLE
额，功能有点不理解

### ISSUE THREAD

**Issue by lucenli** [cnwangjie/better-onetab#38]
当弹出列表中的项被点击时的行为   恢复

我有点没理解，这个是什么意思呢。。。。

**Comment by cnwangjie** [comment]
其实就是打开啦:joy:

**Comment by lucenli** [comment]
_当列表中的一项被点击时的行为  打开/打开并移除_
这一项应该是控制打开的。。。这个我理解

但是_当弹出列表中的项被点击时的行为 恢复/恢复至新窗口_这一项怎么会是控制打开的呢？

我试了下分别选择，恢复和恢复至新窗口
在点击列表中的网页上，都是直接打开新的标签页然后打开那个网页，没差啊。。。

**Comment by cnwangjie** [comment]
弹出列表是点击图标时弹出的简易列表，和详细列表页面中的项目不一样哒:sweat_smile:

你把点击图标时的行为设为（弹出简易列表）试试看

**Comment by lucenli** [comment]
> 弹出列表是点击图标时弹出的简易列表，和详细列表页面中的项目不一样哒😅
> 
> 你把点击图标时的行为设为（弹出简易列表）试试看

原来如此！！明白了，多谢！
