### ISSUE TITLE
扩展不错. 支持移动分组. 几个建议

### ISSUE THREAD

**Issue by V0idk** [cnwangjie/better-onetab#4]
* onetab有个选项, 点击“恢复全部”或恢复单个标签页：将它们保留在您的OneTab列表. 你这里的设计是固定列表...所以我希望有个默认固定的选项或者类似onetab的设计
* 直接拖拽分组来改变顺序

**Comment by cnwangjie** [comment]
@V0idk 感谢你的建议

> 所以我希望有个默认固定的选项或者类似onetab的设计

已经加入了默认固定新的列表的选项

> 直接拖拽分组来改变顺序

分组排序是刚刚加的,之后可能会改成拖拽改变顺序
