### ISSUE TITLE
Allow to restore list appended at the end of the tabs-bar

### ISSUE THREAD

**Issue by Pictor13** [cnwangjie/better-onetab#41]
Extension version: 1.3.7
Browser version: 69.0.3497.100
Operating system: OSX 10.11.6
Problem description: restoring tabs doesn't respect a natural expected behaviour.
 
Actual behavior: when restoring a list into a windows that already has tabs, the list tabs are restored at the beginning of the tab bar.
 
<img width="197" alt="screen shot 2018-09-20 at 12 14 27" src="https://user-images.githubusercontent.com/6748874/45812524-4ca68100-bcd0-11e8-980d-64d31802acf3.png">

Expected behavior: when restoring a list into a windows that already has tabs, the list tabs are restored at the end of the tab bar, after all the current tabs.

<img width="217" alt="screen shot 2018-09-20 at 12 27 48" src="https://user-images.githubusercontent.com/6748874/45813621-61384880-bcd3-11e8-8c19-cfecf705bc18.png">

Reproduce step:
1. show simple list popup
2. click the list to restore

This is more a suggestion than a bug, since I am not sure if the behaviour should be unique or decided by a setting/option.
To me and my workflow is more natural to have the tabs appended at the end of the tab-bar, but maybe the current behaviour fits the workflow of somebody else.

**Comment by cnwangjie** [comment]
Thank you for your suggestion. I usually restore the list in a new window or manually open one of them so I did not notice it. But I think it is a very useful feature. I prefer to add an option for new features to allow the user to decide whether to enable it. Could you submit a PR for this? Or I can add it some days later.

**Comment by cnwangjie** [comment]
I've added an option for this feature in version 1.3.9.

**Comment by Pictor13** [comment]
Thank you, you are amazing! 👍
