### ISSUE TITLE
How can I keep Tab List open while clicking an item in the list?

### ISSUE THREAD

**Issue by spxt4928** [cnwangjie/better-onetab#43]
I use this feature a lot when using OneTab. Sometimes I want to just open some of the items in the tab list. So I need to keep the tab list open and stay at the same page while opening the items and removing them.
Is there some way to do it in version 1.3.7?

**Comment by cnwangjie** [comment]
You can hold the `ctrl` and click the link and it will be opened at a new tab but not switch to. Hope this could help you.

**Comment by spxt4928** [comment]
This works! Thanks!

**Comment by jimbo1qaz** [comment]
Is it possible to make this "don't switch" behavior default?
