### ISSUE TITLE
Original tab title instead of "untitled" in the simple list

### ISSUE THREAD

**Issue by spxt4928** [cnwangjie/better-onetab#45]
Usually I prefer storing selected tabs separately to grouping tabs together. So after I store several tabs, I would always see a lot of "[1] untitled" items in the simple list. I would like to suggest that show the original tab title in the simple list instead of "untitled" for those single tabs. This way, we could better identify those non-grouped tabs to open. As for the grouped items, we can make those titles indented under the group name to demonstrate that those items form a group.

**Comment by cnwangjie** [comment]
This a good idea.
