### ISSUE TITLE
添加一个新的操作选项：将标签收入BetterOneTab后在新标签页自动打开标签页列表

### ISSUE THREAD

**Issue by WitherZuo** [cnwangjie/better-onetab#64]
可以添加一个新的选项，在将标签收入到BetterOneTab中后，自动创建一个新标签页并自动打开标签页列表，可以省去单击BetterOneTab按钮的步骤。

**Comment by cnwangjie** [comment]
现在的设定是如果储存了一个窗口或多个窗口的所有标签后会自动打开一个列表。然而还有人希望在这种情况下也不要打开列表，所以现在有一个选项可以阻止这个行为。:joy:之后可能会改成运行设置自动打开列表页面的情况。
