### ISSUE TITLE
Sync Conflict

### ISSUE THREAD

**Issue by TBLim** [cnwangjie/better-onetab#66]
扩展版本 (extension version): 1.3.11
浏览器版本 (browser version): Version 70.0.3538.77 (Official Build) (64-bit)
操作系统 (operating system): MacOS 10.14.1 (18B75)
问题描述 (problem description): 
Upon using my Google account to sync my lists on 2 different Macbook Chrome, conflict always happen.
实际行为 (actual behavior): 
There is a conflict when sync with server.
Syncing tab lists failed
Remote update time: Wed, November 7th , 22:46:38
Local update time: Wed, November 7th , 22:45:26
Remote lists items
期望行为 (expected behavior): 
The lists on both Macbook's Chrome should be synced. 
重现步骤 (reproduce step):
1. Login using Gmail to sync on both system's Chrome.
2. Press Cloud sync buttion on Tab Lists

![image](https://user-images.githubusercontent.com/18502758/48182420-07b0d980-e366-11e8-8fac-96645502fa94.png)

**Comment by cnwangjie** [comment]
Thank you for your reports. It is a bug caused by handling conflicts objects incorrectly. After new version released will avoid letting the user resolve conflicts. You can turn off the sync service temporarily.
