### ISSUE TITLE
Right click, store selected tabs often doesn't work the first time

### ISSUE THREAD

**Issue by mishaxz** [cnwangjie/better-onetab#74]
浏览器版本 (browser version): Vivaldi 2.1.1337.36 (Stable channel) (64-bit)

don't know if this problem occurs in chrome or not. But I use vivaldi (which is based on chromium) and this problem occurs most of the time I try to store the selected tab.

操作系统 (operating system): Windows 10 and Ubuntu 18.10

重现步骤 (reproduce step):

right click page

better one tab

store selected tabs (1)

... nothing happens (usually, sometimes it works.. but usually not)

store selected tabs (1)

works this time  (always works the 2nd time)

**Comment by cnwangjie** [comment]
Hi, thank you for your reports. I've published a new version with the patch fix this problem.
