### ISSUE TITLE
BOT (BetterOneTab ;-) ) is extremely slow when many links/groups are stored

### ISSUE THREAD

**Issue by rakoczy** [cnwangjie/better-onetab#78]
扩展版本 (extension version): 1.3.11
浏览器版本 (browser version):  Firefox Quantum 63.0.3 (64-bit)
操作系统 (operating system): Windows 7 (64-bit)
问题描述 (problem description): Just after installing BOT I imported into it almost 4000 links in more than 430 groups in OneTab format. It took so much time that FF displayed a warning about extension slowing down the browser. Then I tried to rename a group (BTW "RETITLE" isn't the best term for the operation...).
Yhis operation was so slow that it was close to impossible to edit the two-dozen characters group name. Also an attempt to change of group order (with arrow shown on the right side of the list beside title line) leads to several seconds long lags.
实际行为 (actual behavior):  
 
期望行为 (expected behavior): Faster work - if possible...
 
重现步骤 (reproduce step): Load 4k links and try :-)

BTW. The extension is really better than OneTab, despite the fact it is still very young ;-)  Congrats!
I hope it is stable...

**Comment by cnwangjie** [comment]
Thank you for your trial and reports. It is a known problem. There is already an issue (#55 ) with similar problems. I am trying to solve performance problems in the new version. This is why the new version has not been released for a long time. :)
