### ISSUE TITLE
Clicking the simple list restores only ONE tab

### ISSUE THREAD

**Issue by nmhung1985** [cnwangjie/better-onetab#8]
扩展版本 (extension version): Newest - 05 Aug
浏览器版本 (browser version): Chrome 67
操作系统 (operating system): Windows 10
问题描述 (problem description):  Set the app icon to show simple list. When clicking the simple list, it only restored ONE tab.
 
实际行为 (actual behavior): 
 
期望行为 (expected behavior): When clicking the app icon to show simple list, and continue to click the simple list, it should have opened ALL saved tabs.
 
重现步骤 (reproduce step): In Options, set the app icon's behaviour when clicked to "Popup simple list". Now try saving all tabs in your current window. Next, click the app icon to show the simple list that containing saved tabs. Clicking on that simple list, only ONE tab would be restored.

**Comment by cnwangjie** [comment]
@nmhung1985 thanks for the report. It is fixed in v1.1.3 published today
