### ISSUE TITLE
不能同步

### ISSUE THREAD

**Issue by thetaworld** [cnwangjie/better-onetab#82]
扩展版本 (extension version): 
- Version: 1.3.11

浏览器版本 (browser version): 

- 版本 70.0.3538.110（正式版本） （64 位）

操作系统 (operating system): 

- window10

问题描述 (problem description): 

- 有时候授权页面不能正确加载 
 ![image](https://user-images.githubusercontent.com/36735442/50127639-f33cf680-02ac-11e9-873c-7303c76fa259.png)
- 即使授权页面加载成功，也不能得到正确（正常能使用）的授权

**Comment by cnwangjie** [comment]
感谢反馈，这是个已知的问题。当前的授权方式不太稳定。新版本会改变授权的方式以解决这个问题。

(duplicated with #35)
