### ISSUE TITLE
Unable to add storage sites

### ISSUE THREAD

**Issue by luispo** [cnwangjie/better-onetab#83]
扩展版本 (extension version): 
浏览器版本 (browser version): 
操作系统 (operating system): 
问题描述 (problem description): 
 
实际行为 (actual behavior): 
 
期望行为 (expected behavior): 
 
重现步骤 (reproduce step):

**Comment by luispo** [comment]
Using both Chrome and Firefox (C:  73.0.3642.0 (Official Build) dev (64-bit), F: 65.0b5 (64-bit)), I was unable to add either Google or GitHub as the site to store tab lists. With Google, on both C and F, I received a message (from memory) that authorization was impossible. With Git, on C but not F I seemed to complete the process but then nothing seemed to happen. I'll try more. With F and GitHub, similar message as with Google and Chrome. 

For both browsers, I am using ad blockers and tracker blockers but that ought not to be relevant, given the domains in question.

Otherwise, it's a great idea, to have a storage space for tab lists.

**Comment by luispo** [comment]
sorry, pressed wrong button.

**Comment by geoervin** [comment]
I have same experience across 3 different systems. It goes through the process but does not stick. Mostly using Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by cnwangjie** [comment]
Hi, do you mean it is unable to process the authorization with the sync server? It seems a server error. I've restarted the server and it should be recovered. Besides, data of lists is not actually stored on the sites of Google or Github but on a server I built personally. Authorizing with Google or Github account just for identifying the user. Sorry, I can't provide a completely stable service as a personal project.

**Comment by luispo** [comment]
> On 2018/12/21, at 10:34, Yunhao Zhang <notifications@github.com> wrote:
> 
> Hi, do you mean it is unable to process the authorization with the sync server?

It seems that way. I just tried it again with Firefox (dev) and the process stalled as Google (in this case) was seeking to authorize me so as to share my basic info with your server. BTW, that's kind of sharing gives me pause; other methods—such as using one's Google Drive, an option you also have, though it's not clear *whose* drive is being used—seem preferable. It's probably in your interest to clear up the privacy / security policies for users.


> It seems a server error. I've restarted the server and it should be recovered.

It was working better, but still stalling. 

> Besides, data of lists is not actually stored on the sites of Google or Github but on a server I built personally.

That is what it seems like but it was not clear prior to trying that that was what I was doing. Given the security issues involved—for some, could be major—it's best to be upfront about where the data is being stored.

> Authorizing with Google or Github account just for identifying the user.

I had figured that out. But let's make that clear upfront? Eg,

 "Your data will not be stored on Google's nor GitHub's servers. They will be stored on my, experimental, server. By using Google or GitHub to authorize the storage of your data on my server you enable the identification of your repository. Keep in mind that this is an experimental server—a Beta. You can also use your own Google Drive to store this data."
 (Is this correct?)

> Sorry, I can't provide a completely stable service as a personal project.

Good lord, no one want's that :-) We all have lots of server space. The issue is retrieving inadvertently lost lists of tabs, and for that, one could use one's own G Drive or whatever drive (eg, Dropbox). You offer, it seems, something like that already. So, go with that, please, over your own drive, yes?

Thanks for the speedy reply!

BTW, another issue—I should file it?—relates to font/graphic layout with Firefox. The arrows don't manifest using some fonts, eg, Apple GothicNeo. They do in Chrome using the same font. Playing with the various graphics and fonts was easy enough to do but I was not able to produce a consistent result. I was using Stylus and the built-in dev tools that the browsers offer, as well as an editor (BBEdit).

Regards,
Louis

**Comment by luispo** [comment]
FWIW, checking what services are able to use my Google identity I notice that better onetab is listed, and has been since this morning. So, it worked. 
-Louis

**Comment by cnwangjie** [comment]
> I just tried it again with Firefox (dev) and the process stalled as Google (in this case) was seeking to authorize me so as to share my basic info with your server.

Yes, if you are interested in the specific principles, you can learn more from Google's documentation.

https://developers.google.com/identity/protocols/OAuth2

> such as using one's Google Drive, an option you also have, though it's not clear *whose* drive is being used—seem preferable. It's probably in your interest to clear up the privacy / security policies for users.

It requires another authorization to allow the application to access the user's Google Drive. The data will be saved in the authorized account. I think I will add some more instructions for this later.

> I had figured that out. But let's make that clear upfront? Eg,
>
>  "Your data will not be stored on Google's nor GitHub's servers. They will be stored on my, experimental, server. By using Google or GitHub to authorize the storage of your data on my server you enable the identification of your repository. Keep in mind that this is an experimental server—a Beta. You can also use your own Google Drive to store this data."
>  (Is this correct?)

It is almost correct.

> Good lord, no one want's that :-) We all have lots of server space. The issue is retrieving inadvertently lost lists of tabs, and for that, one could use one's own G Drive or whatever drive (eg, Dropbox). You offer, it seems, something like that already. So, go with that, please, over your own drive, yes?

I think so. Anyone can export the data and save them if they want. But there are still many users who want a more convenient way to sync the data across platforms. I also tried to achieve it. 

> The arrows don't manifest using some fonts, eg, Apple GothicNeo. They do in Chrome using the same font. Playing with the various graphics and fonts was easy enough to do but I was not able to produce a consistent result. I was using Stylus and the built-in dev tools that the browsers offer, as well as an editor (BBEdit).

I do not quite understand you, Is it related to the display of the extension in different browsers?

**Comment by luispo** [comment]
> On 2018/12/22, at 02:10, Yunhao Zhang <notifications@github.com> wrote:
> 
> I think so. Anyone can export the data and save them if they want. But there are still many users who want a more convenient way to sync the data across platforms. I also tried to achieve it.

Understood. Perhaps clear language that the Google Drive is the user's, and then use a script that save to it. Perhaps modifying the standard Google save-to-drive one. Obviously, users would have to a) have a usable G drive, b) go through the process of enabling one-click saving of the tab list to it. You do this already, I believe, or nearly.

The main point is clarifying to the user what's going on. As this is beta and as you use an open license (MIT? I believe) and have a responsiveness that's great, I'm pretty optimistic that the rough parts would be smoothed over quickly.




> 
> The arrows don't manifest using some fonts, eg, Apple GothicNeo. They do in Chrome using the same font. Playing with the various graphics and fonts was easy enough to do but I was not able to produce a consistent result. I was using Stylus and the built-in dev tools that the browsers offer, as well as an editor (BBEdit).
> 
> I do not quite understand you, Is it related to the display of the extension in different browsers?

Perhaps. I then tried anew with with Chrome (dev) and also Firefox (dev) and the extension's arrows were in both cases inconsistently presented, and in F's case, hardly at all. My default fonts included Google's Open Sans as well as Apple's NeoGothic. FWIW, I tend to eliminate most images and graphics from sites I visit and use and am well aware that nearly all of humanity has a different approach to the Web and actually likes nice graphics. :-) But, still, nice graphics don't mean much if they are kludged.

Cheers,
Louis

> 
>

**Comment by scottrigby** [comment]
Quick question, on MacOS, is the drive integration with Google's newer Backup and Sync app? AFAIK Google is discontinuing the local Drive app.
