### ISSUE TITLE
Date collision with title

### ISSUE THREAD

**Issue by efenner** [cnwangjie/better-onetab#86]
扩展版本 (extension version): 1.3.11
浏览器版本 (browser version): 71.0.3578.98
操作系统 (operating system): MacOS High Sierra 10.13.6
问题描述 (problem description): Named groups old enough to have a full date attached as opposed to a relative date experience a collision between the long date and the title
 
实际行为 (actual behavior): 
 
期望行为 (expected behavior): There should be more space between the date and the title so that this does not happen, even with long dates.
 
重现步骤 (reproduce step):

**Comment by efenner** [comment]
<img width="815" alt="screen shot 2019-01-09 at 11 30 01" src="https://user-images.githubusercontent.com/17870148/50923833-c2129a80-1402-11e9-98aa-32360f61a672.png">

**Comment by rsun-thoughtworks** [comment]
这个是老版本，不知道还维护不维护。

**Comment by cnwangjie** [comment]
Hi! Thank you for your reports. I'll try to publish a version based on
current released version to fix this and others similar problems.
