### ISSUE TITLE
Group titles are small

### ISSUE THREAD

**Issue by efenner** [cnwangjie/better-onetab#87]
扩展版本 (extension version): 1.3.11
浏览器版本 (browser version): 71.0.3578.98
操作系统 (operating system): MacOS High Sierra 10.13.6
问题描述 (problem description): The titles of tab groups appear small in comparison to other elements on the page. I would expect them to be at least as large as the text giving the number of tabs in the group. Instead, they are the same size as the date (which is less important information).
 
实际行为 (actual behavior): 
 
期望行为 (expected behavior): 
 
重现步骤 (reproduce step):

**Comment by efenner** [comment]
Newest update made this issue even more apparent as the titles seem to no longer be bold.
<img width="685" alt="screen shot 2019-01-18 at 10 35 23" src="https://user-images.githubusercontent.com/17870148/51406028-cb8bb900-1b0c-11e9-96f1-b3cd8058b7ac.png">

In my opinion the importance hierarchy should be Title>Date>=Tab Count, while right now it is pretty clearly Tab Count>Date>>Title.

**Comment by cnwangjie** [comment]
HI, it seems a common problem for the users of high resolution displays. I will add an option to allow user choice larger font size in the new version.
