### ISSUE TITLE
Add option to disable fancy graphics -- especially the animations

### ISSUE THREAD

**Issue by bogmihdav** [cnwangjie/better-onetab#92]
I am trying to run it on a Raspberry Pi, and the visuals are laggy. Expanding and collapsing are particularly slow.
An option to disable fancy stuff like animations would be helpful.

**Comment by VelocityRa** [comment]
Super laggy on a beefy machine too, if you have lots of saved tabs (but not unreasonably many).

**Comment by bogmihdav** [comment]
Thank you very much for the support

> BTW, in fact, graphic interface and modern browser themselves required a large number of system resources. I don't recommend to use Chrome in a low-performance device. Especially on old computers or single-chip microcomputer like Raspberry Pi.

I know I'm somewhat responsible for the choppiness by using it on a Pi, but I'm comparing Better One Tab's performance with other pages that I also view on the same hardware and browser. I think disabling animations would be helpful either way.

Looking forward to v1.4
