### ISSUE TITLE
Add same behaviour as Onetab on click

### ISSUE THREAD

**Issue by caiodev** [cnwangjie/better-onetab#95]
I think when you clicked the Better onetab icon, it should automatically store all tabs on that window like Onetab does. That's something i'd like to see in Better onetab

**Comment by cnwangjie** [comment]
Hi, you can change the behavior when icon is clicked in the options page. Hope this could help you.

**Comment by dagelf** [comment]
Can you make this the default? I previously installed and immediately uninstalled it because I didn't know this... and I would presume others would do the same.... you know... us human beings can be quite fickle.. Thanks
